version: "3"
services:

  timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    hostname: ${HOST_NAME}
    environment:
      - EXTERNAL_CONF=/users
      - SHARE_NAME=${SHARE_NAME}
      - TZ=Europe/Berlin
    networks:
      timemachine:
        ipv4_address: ${IPV4_ADDRESS}
    volumes:
      - ${BACKUP_DIR}:/opt
      - ./users:/users
    restart: unless-stopped

networks:
  timemachine:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${SUBNET}
          ip_range: ${IP_RANGE}
          gateway: ${GATEWAY}
